### ISSUE TITLE
¿Podrias facilitar un set de datos para probar en desarrollo?

### ISSUE THREAD

**Issue by carlosfernandezcabrero** [franjpr/boe-backend#26]
Hola,

Por favor, ¿Podrias facilitar un set de datos para probar en desarrollo?, por ejemplo, un txt con insert para meter en la base de datos.

Un saludo, muchas gracias

**Comment by 0fprod** [comment]
> Hola,
> 
> Por favor, ¿Podrias facilitar un set de datos para probar en desarrollo?, por ejemplo, un txt con insert para meter en la base de datos.
> 
> Un saludo, muchas gracias

Hola! Disculpa la demora. En lo que tenga un rato te lo puedo compartir como fichero .json
Por curiosidad.. para qué lo vas a usar?

**Comment by 0fprod** [comment]
@carlosfernandezcabrero  Este es un fichero .txt con el contenido en json con 4 meses de datos desde 2021-03-01 hasta 2021-07-01.
Si quieres otras fechas puedes pedirlos desde el [swagger](https://boe-backend.vercel.app/#/Contratos/ContratosController_getRangoDeFecha) 
[response_1663831673089.txt](https://github.com/franjpr/boe-backend/files/9623411/response_1663831673089.txt)

**Comment by carlosfernandezcabrero** [comment]
@franjpr Hola! Quiero utilizar el fichero para tener datos que meter en la base datos que me he creado localmente y conectado con el backend para tratar de ver si veo porque me pasa lo comentado en la issue #21.

Muchas gracias !!
